In [29]:
import numpy as np
import pandas as pd

In [30]:
df=pd.read_csv('train.csv',usecols=['Survived','Age','SibSp','Parch','Fare'])

In [31]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [32]:
df['family']=df['SibSp']+df['Parch']

In [33]:
df.head()

   Survived   Age  SibSp  Parch     Fare  family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [34]:
df.dropna(inplace=True)

In [35]:
df

     Survived   Age  SibSp  Parch     Fare  family
0           0  22.0      1      0   7.2500       1
1           1  38.0      1      0  71.2833       1
2           1  26.0      0      0   7.9250       0
3           1  35.0      1      0  53.1000       1
4           0  35.0      0      0   8.0500       0
..        ...   ...    ...    ...      ...     ...
885         0  39.0      0      5  29.1250       5
886         0  27.0      0      0  13.0000       0
887         1  19.0      0      0  30.0000       0
889         1  26.0      0      0  30.0000       0
890         0  32.0      0      0   7.7500       0

[714 rows x 6 columns]

In [36]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=False)

In [38]:
from sklearn.preprocessing import Binarizer
from sklearn.compose import ColumnTransformer

In [39]:
trf=ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [40]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

In [41]:
X_train_trf

array([[  0.    ,  36.    ,  13.    ],
       [  1.    ,  25.    ,  41.5792],
       [  0.    ,  35.    ,  26.    ],
       ...,
       [  0.    ,  46.    ,  79.2   ],
       [  1.    ,  26.    ,   7.8542],
       [  1.    ,  45.    , 164.8667]], shape=(571, 3))

In [47]:
X_train_final=pd.DataFrame(X_train_trf,columns=trf.get_feature_names_out())

In [48]:
X_train_final

     bin__family  remainder__Age  remainder__Fare
0            0.0            36.0          13.0000
1            1.0            25.0          41.5792
2            0.0            35.0          26.0000
3            0.0            45.5          28.5000
4            0.0            31.0           7.8542
..           ...             ...              ...
566          0.0            28.0          10.5000
567          0.0            19.0          10.5000
568          0.0            46.0          79.2000
569          1.0            26.0           7.8542
570          1.0            45.0         164.8667

[571 rows x 3 columns]

In [44]:
df

     Survived   Age     Fare  family
0           0  22.0   7.2500       1
1           1  38.0  71.2833       1
2           1  26.0   7.9250       0
3           1  35.0  53.1000       1
4           0  35.0   8.0500       0
..        ...   ...      ...     ...
885         0  39.0  29.1250       5
886         0  27.0  13.0000       0
887         1  19.0  30.0000       0
889         1  26.0  30.0000       0
890         0  32.0   7.7500       0

[714 rows x 4 columns]

In [45]:
X_train

      Age      Fare  family
387  36.0   13.0000       0
685  25.0   41.5792       3
20   35.0   26.0000       0
331  45.5   28.5000       0
396  31.0    7.8542       0
..    ...       ...     ...
883  28.0   10.5000       0
238  19.0   10.5000       0
789  46.0   79.2000       0
704  26.0    7.8542       1
856  45.0  164.8667       2

[571 rows x 3 columns]