In [1]:
import numpy as np
import pandas as pd

In [55]:
date=pd.read_csv('orders.csv',usecols=['date'])
time=pd.read_csv('messages.csv',usecols=['date'])

In [56]:
date.head(2)

         date
0  2019-12-10
1  2018-08-15

In [57]:
time.head(2)

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00

In [58]:
date.info()  #date and time column by default string thake eke date type e niye giye kaj korte hoi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [59]:
##Working with dates

In [60]:
date['date']=pd.to_datetime(date['date'])

In [61]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [62]:
#extract year

In [63]:
date['date_year']=date['date'].dt.year
date.head()

        date  date_year
0 2019-12-10       2019
1 2018-08-15       2018
2 2018-10-23       2018
3 2019-08-17       2019
4 2019-01-06       2019

In [64]:
#extract month
date['date_month']=date['date'].dt.month
date.head()

        date  date_year  date_month
0 2019-12-10       2019          12
1 2018-08-15       2018           8
2 2018-10-23       2018          10
3 2019-08-17       2019           8
4 2019-01-06       2019           1

In [65]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

        date  date_year  date_month date_month_name
0 2019-12-10       2019          12        December
1 2018-08-15       2018           8          August
2 2018-10-23       2018          10         October
3 2019-08-17       2019           8          August
4 2019-01-06       2019           1         January

In [66]:
#extrac day
date['date_day']=date['date'].dt.day
date.head()

        date  date_year  date_month date_month_name  date_day
0 2019-12-10       2019          12        December        10
1 2018-08-15       2018           8          August        15
2 2018-10-23       2018          10         October        23
3 2019-08-17       2019           8          August        17
4 2019-01-06       2019           1         January         6

In [67]:
#day of week
date['date_day_of_week']=date['date'].dt.dayofweek
date.head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week
0,2019-12-10,2019,12,December,10,1
1,2018-08-15,2018,8,August,15,2
2,2018-10-23,2018,10,October,23,1
3,2019-08-17,2019,8,August,17,5
4,2019-01-06,2019,1,January,6,6

In [68]:
#day of week -> name
date['date_day_of_week_name']=date['date'].dt.day_name()
date.head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [69]:
# is weekend?
date['date_is_weekend']=np.where(date['date_day_of_week_name'].isin(['Friday','Saturday']),1,0)
date.head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,0

In [70]:
#extract week of the year
date['date_week']=date['date'].dt.isocalendar().week
date.head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,0,1

In [71]:
#extract time elapsed between dates
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 7, 29, 12, 21, 27, 556417)

In [72]:
today-date['date']

0     2423 days 12:21:27.556417
1     2905 days 12:21:27.556417
2     2836 days 12:21:27.556417
3     2538 days 12:21:27.556417
4     2761 days 12:21:27.556417
                 ...
995   2851 days 12:21:27.556417
996   2792 days 12:21:27.556417
997   2640 days 12:21:27.556417
998   2705 days 12:21:27.556417
999   2479 days 12:21:27.556417
Name: date, Length: 1000, dtype: timedelta64[ns]

In [73]:
(today-date['date']).dt.days

0      2423
1      2905
2      2836
3      2538
4      2761
       ...
995    2851
996    2792
997    2640
998    2705
999    2479
Name: date, Length: 1000, dtype: int64

In [74]:
((today-date['date']).dt.days)/30

0      80.766667
1      96.833333
2      94.533333
3      84.600000
4      92.033333
         ...
995    95.033333
996    93.066667
997    88.000000
998    90.166667
999    82.633333
Name: date, Length: 1000, dtype: float64

In [75]:
((today-date['date']).dt.days)//30

0      80
1      96
2      94
3      84
4      92
       ..
995    95
996    93
997    88
998    90
999    82
Name: date, Length: 1000, dtype: int64

In [76]:
#time column

In [77]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [78]:
time['date']=pd.to_datetime(time['date'])

In [79]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [80]:
time['hour']=time['date'].dt.hour

In [81]:
time['min']=time['date'].dt.minute

In [82]:
time['sec']=time['date'].dt.second

In [83]:
time

                   date  hour  min  sec
0   2013-12-15 00:50:00     0   50    0
1   2014-04-29 23:40:00    23   40    0
2   2012-12-30 00:21:00     0   21    0
3   2014-11-28 00:31:00     0   31    0
4   2013-10-26 23:11:00    23   11    0
..                  ...   ...  ...  ...
995 2012-03-16 00:50:00     0   50    0
996 2014-01-23 23:14:00    23   14    0
997 2012-10-15 23:37:00    23   37    0
998 2012-06-21 23:34:00    23   34    0
999 2014-06-19 23:25:00    23   25    0

[1000 rows x 4 columns]

In [84]:
#extract time part
time['time']=time['date'].dt.time

In [85]:
time

                   date  hour  min  sec      time
0   2013-12-15 00:50:00     0   50    0  00:50:00
1   2014-04-29 23:40:00    23   40    0  23:40:00
2   2012-12-30 00:21:00     0   21    0  00:21:00
3   2014-11-28 00:31:00     0   31    0  00:31:00
4   2013-10-26 23:11:00    23   11    0  23:11:00
..                  ...   ...  ...  ...       ...
995 2012-03-16 00:50:00     0   50    0  00:50:00
996 2014-01-23 23:14:00    23   14    0  23:14:00
997 2012-10-15 23:37:00    23   37    0  23:37:00
998 2012-06-21 23:34:00    23   34    0  23:34:00
999 2014-06-19 23:25:00    23   25    0  23:25:00

[1000 rows x 5 columns]

In [87]:
#time difference
today-time['date']

0     4609 days 11:31:27.556417
1     4473 days 12:41:27.556417
2     4959 days 12:00:27.556417
3     4261 days 11:50:27.556417
4     4658 days 13:10:27.556417
                 ...
995   5248 days 11:31:27.556417
996   4569 days 13:07:27.556417
997   5034 days 12:44:27.556417
998   5150 days 12:47:27.556417
999   4422 days 12:56:27.556417
Name: date, Length: 1000, dtype: timedelta64[ns]

In [88]:
#time difference in seconds
(today-time['date'])/np.timedelta64(1,'s')

0      3.982591e+08
1      3.865129e+08
2      4.285008e+08
3      3.681930e+08
4      4.024986e+08
           ...
995    4.534687e+08
996    3.948088e+08
997    4.349835e+08
998    4.450060e+08
999    3.821074e+08
Name: date, Length: 1000, dtype: float64

In [89]:
#time difference in minutes
(today-time['date'])/np.timedelta64(1,'m')

0      6.637651e+06
1      6.441881e+06
2      7.141680e+06
3      6.136550e+06
4      6.708310e+06
           ...
995    7.557811e+06
996    6.580147e+06
997    7.249724e+06
998    7.416767e+06
999    6.368456e+06
Name: date, Length: 1000, dtype: float64

In [90]:
#time difference in hours
(today-time['date'])/np.timedelta64(1,'h')

0      110627.524321
1      107364.690988
2      119028.007655
3      102275.840988
4      111805.174321
           ...
995    125963.524321
996    109669.124321
997    120828.740988
998    123612.790988
999    106140.940988
Name: date, Length: 1000, dtype: float64