In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer

In [3]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [4]:
df

     Survived  Pclass   Age     Fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3   NaN  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [5]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [12]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [13]:
x

     Pclass   Age     Fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3   NaN  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [14]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [16]:
knn=KNNImputer()
x_train_trf=knn.fit_transform(X_train)
x_test_trf=knn.transform(X_test)

In [19]:
pd.DataFrame(x_train_trf,columns=X_train.columns)

     Pclass   Age      Fare
0       3.0  27.0    7.7958
1       1.0  58.0  146.5208
2       3.0  18.0    7.4958
3       1.0  26.0   78.8500
4       3.0  22.0    7.8958
..      ...   ...       ...
707     1.0  38.4   79.2000
708     3.0  33.0   56.4958
709     2.0  54.0   26.0000
710     3.0  20.0    7.9250
711     2.0  28.0   24.0000

[712 rows x 3 columns]

In [22]:
knn=KNNImputer(n_neighbors=6,weights='distance')
x_train_trf=knn.fit_transform(X_train)
x_test_trf=knn.transform(X_test)

In [23]:
pd.DataFrame(x_train_trf,columns=X_train.columns)

     Pclass        Age      Fare
0       3.0  27.000000    7.7958
1       1.0  58.000000  146.5208
2       3.0  18.000000    7.4958
3       1.0  26.000000   78.8500
4       3.0  22.000000    7.8958
..      ...        ...       ...
707     1.0  43.333333   79.2000
708     3.0  28.666667   56.4958
709     2.0  54.000000   26.0000
710     3.0  20.000000    7.9250
711     2.0  28.000000   24.0000

[712 rows x 3 columns]