In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','SibSp','Parch','Survived'])

In [3]:
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
886         0       2  27.0      0      0
887         1       1  19.0      0      0
888         0       3   NaN      1      2
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[891 rows x 5 columns]

In [4]:
df.dropna(inplace=True)

In [5]:
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
885         0       3  39.0      0      5
886         0       2  27.0      0      0
887         1       1  19.0      0      0
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[714 rows x 5 columns]

In [7]:
#feature construction
df['Family_size']=df['SibSp']+df['Parch']+1

In [8]:
df

     Survived  Pclass   Age  SibSp  Parch  Family_size
0           0       3  22.0      1      0            2
1           1       1  38.0      1      0            2
2           1       3  26.0      0      0            1
3           1       1  35.0      1      0            2
4           0       3  35.0      0      0            1
..        ...     ...   ...    ...    ...          ...
885         0       3  39.0      0      5            6
886         0       2  27.0      0      0            1
887         1       1  19.0      0      0            1
889         1       1  26.0      0      0            1
890         0       3  32.0      0      0            1

[714 rows x 6 columns]

In [9]:
def func(num):
    if num==1:
        return 0
        #alone
    elif num>1 and num<=4:
        return 1
        #small family
    else:
        return 2
        #large family

In [10]:
df['Family_type']=df['Family_size'].apply(func)

In [11]:
df

     Survived  Pclass   Age  SibSp  Parch  Family_size  Family_type
0           0       3  22.0      1      0            2            1
1           1       1  38.0      1      0            2            1
2           1       3  26.0      0      0            1            0
3           1       1  35.0      1      0            2            1
4           0       3  35.0      0      0            1            0
..        ...     ...   ...    ...    ...          ...          ...
885         0       3  39.0      0      5            6            2
886         0       2  27.0      0      0            1            0
887         1       1  19.0      0      0            1            0
889         1       1  26.0      0      0            1            0
890         0       3  32.0      0      0            1            0

[714 rows x 7 columns]

In [12]:
#feature splitting

In [15]:
df=pd.read_csv('train.csv')

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [23]:
df['Title']=df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [24]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr